-- Nothing... --
shared.its_a_cat, shared.its_a_fox, shared.its_a_secrect = "shiro", "lusha", "124590"
shared._numberX = 2
_G.HHxScripts = {
    ["Its_Matched"] = {
        [7436755782] = "https://raw.githubusercontent.com/HoangHienXScripts/Scripts/refs/heads/obfucated/Games/GrowAGarden_Obf.luau"
    },
    ["Its_Not_Matched"] = {
        "https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source",
        "https://raw.githubusercontent.com/HoangHienXScripts/Scripts/refs/heads/modified/InfiniteYield/MainSource.luau"
    }
}

-- End... --
