-- Nothing... --
shared.its_a_cat, shared.its_a_fox, shared.its_a_secrect = "shiro", "lusha", "124590"
shared._numberX = 2
_G.HHxScripts = {
    ["Its_Matched"] = {
        -- Grow a garden: simple harvesting plants --
        [7436755782] = "https://raw.githubusercontent.com/HoangHienXScripts/Scripts/refs/heads/obfucated/Games/GrowAGarden_Obf.luau",

        -- 99 Day/Night with Campfire: simple items esp --
        [7326934954] = "https://raw.githubusercontent.com/HoangHienXScripts/Scripts/refs/heads/obfucated/Games/99Days_ItemsESP.luau"
    },
    ["Its_Not_Matched"] = {
        "https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source",
        "https://raw.githubusercontent.com/HoangHienXScripts/Scripts/refs/heads/modified/InfiniteYield/MainSource.luau"
    },
    ["BlackList"] = {
        -- Blue Lock Rivals --
        [6325068386] = "game.Players.LocalPlayer:Kick('This game, i dont liked it... so leave!')"
    }
}

-- End... --
